kafka.constants:
  url: "localhost:9092"
  hub.topic: "telemetry.hubs.v1"
  snapshot.topic: "telemetry.snapshots.v1"
grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext